"""
UTP Course Catalog - Pre-loaded courses for all programmes and semesters.
Students can select their programme and semester to auto-populate courses.
"""

UTP_PROGRAMS = {
    "cs": {
        "name": "Bachelor of Computer Science (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UCB1023", "name": "Computer Systems", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UCB1033", "name": "Object-Oriented Programming", "credits": 3},
                {"code": "UCB1043", "name": "Discrete Mathematics", "credits": 3},
                {"code": "UCB1053", "name": "Data Communication and Network", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UCB2013", "name": "Statistics and Empirical Method", "credits": 3},
                {"code": "UCB2023", "name": "Data & Information Management", "credits": 3},
                {"code": "UCB2033", "name": "Algorithm and Data Structure", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UCB2043", "name": "Software Engineering & HCI", "credits": 3},
                {"code": "UCB2053", "name": "Artificial Intelligence", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UCB3013", "name": "Data Science", "credits": 3},
                {"code": "UCB3023", "name": "Embedded Systems", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UCB3033", "name": "Technopreneurship Team Project", "credits": 3},
                {"code": "UCB3043", "name": "Computer Security", "credits": 3},
                {"code": "UCB3053", "name": "Modelling and Simulation", "credits": 3},
                {"code": "UXX3002", "name": "Minor Elective II", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UCB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UXX4001", "name": "Minor Elective III", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective IV", "credits": 3},
                {"code": "UCB4023", "name": "Core Specialization I", "credits": 3},
                {"code": "UCB4033", "name": "Core Specialization II", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UCB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UXX4003", "name": "Minor Elective V", "credits": 3},
                {"code": "UCB4043", "name": "Core Specialization III", "credits": 3},
                {"code": "UCB4053", "name": "Distributed and Parallel Computing", "credits": 3},
            ],
        }
    },
    "ce": {
        "name": "Bachelor of Computer Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UCB1023", "name": "Computer Systems", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UEB1013", "name": "Electrical Circuit Analysis", "credits": 3},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UCB1033", "name": "Object-Oriented Programming", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UEB1023", "name": "Digital Logic Design", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UCB2033", "name": "Algorithm and Data Structure", "credits": 3},
                {"code": "UEB2013", "name": "Electronics I", "credits": 3},
                {"code": "UEB2023", "name": "Signals and Systems", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UCB1053", "name": "Data Communication and Network", "credits": 3},
                {"code": "UEB2033", "name": "Microprocessor & Microcontroller", "credits": 3},
                {"code": "UEB2043", "name": "Computer Architecture", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UEB3013", "name": "Operating Systems", "credits": 3},
                {"code": "UEB3023", "name": "Embedded Systems Design", "credits": 3},
                {"code": "UEB3033", "name": "Computer Networks", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UEB3043", "name": "Real-Time Systems", "credits": 3},
                {"code": "UEB3053", "name": "VLSI Design", "credits": 3},
                {"code": "UEB3063", "name": "Big Data Analytics", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UEB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UEB4023", "name": "Parallel & Distributed Computing", "credits": 3},
                {"code": "UEB4033", "name": "IoT Systems", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UEB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UEB4043", "name": "Computer Security", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "ee": {
        "name": "Bachelor of Electrical & Electronics Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UEB1013", "name": "Electrical Circuit Analysis", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UEB1023", "name": "Digital Logic Design", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UEB1033", "name": "Electrical Measurements & Instrumentation", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UEB2013", "name": "Electronics I", "credits": 3},
                {"code": "UEB2023", "name": "Signals and Systems", "credits": 3},
                {"code": "UEB2033", "name": "Electromagnetic Theory", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UEB2043", "name": "Electronics II", "credits": 3},
                {"code": "UEB2053", "name": "Control Systems", "credits": 3},
                {"code": "UEB2063", "name": "Power Systems", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UEB3013", "name": "Communication Systems", "credits": 3},
                {"code": "UEB3023", "name": "Power Electronics", "credits": 3},
                {"code": "UEB3033", "name": "Microprocessor & Microcontroller", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UEB3043", "name": "Digital Signal Processing", "credits": 3},
                {"code": "UEB3053", "name": "Electrical Machines", "credits": 3},
                {"code": "UEB3063", "name": "EE Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UEB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UEB4023", "name": "EE Elective II", "credits": 3},
                {"code": "UEB4033", "name": "EE Elective III", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UEB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UEB4043", "name": "EE Elective IV", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "me": {
        "name": "Bachelor of Mechanical Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UMB1013", "name": "Engineering Mechanics - Statics", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UMB1023", "name": "Engineering Mechanics - Dynamics", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UMB1033", "name": "Engineering Drawing & CAD", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UMB2013", "name": "Thermodynamics I", "credits": 3},
                {"code": "UMB2023", "name": "Fluid Mechanics I", "credits": 3},
                {"code": "UMB2033", "name": "Mechanics of Materials", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UMB2043", "name": "Thermodynamics II", "credits": 3},
                {"code": "UMB2053", "name": "Fluid Mechanics II", "credits": 3},
                {"code": "UMB2063", "name": "Materials Science", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UMB3013", "name": "Heat Transfer", "credits": 3},
                {"code": "UMB3023", "name": "Machine Design I", "credits": 3},
                {"code": "UMB3033", "name": "Manufacturing Technology I", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UMB3043", "name": "Dynamics & Control", "credits": 3},
                {"code": "UMB3053", "name": "Machine Design II", "credits": 3},
                {"code": "UMB3063", "name": "ME Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UMB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UMB4023", "name": "ME Elective II", "credits": 3},
                {"code": "UMB4033", "name": "ME Elective III", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UMB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UMB4043", "name": "Manufacturing Technology II", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "chem": {
        "name": "Bachelor of Chemical Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UKB1013", "name": "Introduction to Chemical Engineering", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UKB1023", "name": "Physical Chemistry", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UKB1033", "name": "Organic Chemistry", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UKB2013", "name": "Chemical Engineering Thermodynamics", "credits": 3},
                {"code": "UKB2023", "name": "Fluid Mechanics", "credits": 3},
                {"code": "UKB2033", "name": "Material & Energy Balance", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UKB2043", "name": "Heat Transfer", "credits": 3},
                {"code": "UKB2053", "name": "Mass Transfer", "credits": 3},
                {"code": "UKB2063", "name": "Chemical Reaction Engineering", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UKB3013", "name": "Separation Processes", "credits": 3},
                {"code": "UKB3023", "name": "Process Control", "credits": 3},
                {"code": "UKB3033", "name": "Process Plant Design I", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UKB3043", "name": "Process Plant Design II", "credits": 3},
                {"code": "UKB3053", "name": "Process Safety Engineering", "credits": 3},
                {"code": "UKB3063", "name": "ChemE Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UKB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UKB4023", "name": "ChemE Elective II", "credits": 3},
                {"code": "UKB4033", "name": "ChemE Elective III", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UKB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UKB4043", "name": "ChemE Elective IV", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "civil": {
        "name": "Bachelor of Civil Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UAB1013", "name": "Engineering Mechanics - Statics", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UAB1023", "name": "Civil Engineering Materials", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UAB1033", "name": "Surveying", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UAB2013", "name": "Structural Analysis I", "credits": 3},
                {"code": "UAB2023", "name": "Fluid Mechanics", "credits": 3},
                {"code": "UAB2033", "name": "Geotechnical Engineering I", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UAB2043", "name": "Structural Analysis II", "credits": 3},
                {"code": "UAB2053", "name": "Hydrology & Water Resources", "credits": 3},
                {"code": "UAB2063", "name": "Geotechnical Engineering II", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UAB3013", "name": "Reinforced Concrete Design", "credits": 3},
                {"code": "UAB3023", "name": "Steel Design", "credits": 3},
                {"code": "UAB3033", "name": "Highway Engineering", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UAB3043", "name": "Foundation Engineering", "credits": 3},
                {"code": "UAB3053", "name": "Construction Management", "credits": 3},
                {"code": "UAB3063", "name": "Civil Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UAB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UAB4023", "name": "Civil Elective II", "credits": 3},
                {"code": "UAB4033", "name": "Civil Elective III", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UAB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UAB4043", "name": "Civil Elective IV", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "petro": {
        "name": "Bachelor of Petroleum Engineering (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UPB1013", "name": "Petroleum Geoscience", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UPB1023", "name": "Rock & Fluid Properties", "credits": 3},
                {"code": "UMB2042", "name": "Engineering Mathematics II", "credits": 4},
                {"code": "UPB1033", "name": "Drilling Engineering I", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UPB2013", "name": "Reservoir Engineering I", "credits": 3},
                {"code": "UPB2023", "name": "Production Technology I", "credits": 3},
                {"code": "UPB2033", "name": "Drilling Engineering II", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UPB2043", "name": "Reservoir Engineering II", "credits": 3},
                {"code": "UPB2053", "name": "Production Technology II", "credits": 3},
                {"code": "UPB2063", "name": "Well Logging & Formation Evaluation", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UPB3013", "name": "Reservoir Simulation", "credits": 3},
                {"code": "UPB3023", "name": "Well Test Analysis", "credits": 3},
                {"code": "UPB3033", "name": "Enhanced Oil Recovery", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UPB3043", "name": "Field Development Planning", "credits": 3},
                {"code": "UPB3053", "name": "Petroleum Economics", "credits": 3},
                {"code": "UPB3063", "name": "Petro Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UPB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UPB4023", "name": "Petro Elective II", "credits": 3},
                {"code": "UPB4033", "name": "Petro Elective III", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UPB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UPB4043", "name": "Petro Elective IV", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "ibm": {
        "name": "Bachelor in Business Management (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UBB1013", "name": "Principles of Management", "credits": 3},
                {"code": "UBB1023", "name": "Financial Accounting", "credits": 3},
                {"code": "UBB1033", "name": "Business Mathematics", "credits": 3},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UBB1043", "name": "Microeconomics", "credits": 3},
                {"code": "UBB1053", "name": "Business Statistics", "credits": 3},
                {"code": "UBB1063", "name": "Marketing Management", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UBB2013", "name": "Macroeconomics", "credits": 3},
                {"code": "UBB2023", "name": "Organizational Behaviour", "credits": 3},
                {"code": "UBB2033", "name": "Managerial Accounting", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UBB2043", "name": "Business Finance", "credits": 3},
                {"code": "UBB2053", "name": "Operations Management", "credits": 3},
                {"code": "UBB2063", "name": "Business Law", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UBB3013", "name": "Strategic Management", "credits": 3},
                {"code": "UBB3023", "name": "Human Resource Management", "credits": 3},
                {"code": "UBB3033", "name": "Business Elective I", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UBB3043", "name": "International Business", "credits": 3},
                {"code": "UBB3053", "name": "Business Research Methods", "credits": 3},
                {"code": "UBB3063", "name": "Business Elective II", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UBB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UBB4023", "name": "Business Elective III", "credits": 3},
                {"code": "UBB4033", "name": "Business Elective IV", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective II", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective III", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UBB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UBB4043", "name": "Business Elective V", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective IV", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective V", "credits": 3},
            ],
        }
    },
    "is": {
        "name": "Bachelor of Information Systems (Hons)",
        "semesters": {
            "Semester 1": [
                {"code": "MPU3193", "name": "Penghayatan Etika & Peradaban", "credits": 3},
                {"code": "UCB1013", "name": "Structured Programming", "credits": 3},
                {"code": "UIB1013", "name": "Fundamentals of Information Systems", "credits": 3},
                {"code": "UMB1042", "name": "Engineering Mathematics I", "credits": 4},
                {"code": "UHB1012", "name": "Introduction to Oil & Gas Industry & Sustainable Development", "credits": 1},
            ],
            "Semester 2": [
                {"code": "MPU3213", "name": "Falsafah dan Isu Semasa", "credits": 3},
                {"code": "UHB2012", "name": "Health, Safety & Environment", "credits": 1},
                {"code": "UCB1033", "name": "Object-Oriented Programming", "credits": 3},
                {"code": "UIB1023", "name": "Systems Analysis & Design", "credits": 3},
                {"code": "UCB1053", "name": "Data Communication and Network", "credits": 3},
            ],
            "Semester 3": [
                {"code": "MPU3223", "name": "MPU2 Course", "credits": 3},
                {"code": "UHB2022", "name": "Academic Writing", "credits": 2},
                {"code": "UHB1031", "name": "Co-Curriculum I", "credits": 1},
                {"code": "UCB2013", "name": "Statistics and Empirical Method", "credits": 3},
                {"code": "UCB2023", "name": "Data & Information Management", "credits": 3},
                {"code": "UIB2013", "name": "Web Application Development", "credits": 3},
            ],
            "Semester 4": [
                {"code": "MPU3233", "name": "MPU3 Course", "credits": 3},
                {"code": "UHB2032", "name": "Scientific Inquiry", "credits": 2},
                {"code": "UHB2041", "name": "Co-Curriculum II", "credits": 1},
                {"code": "UIB2023", "name": "Enterprise Resource Planning", "credits": 3},
                {"code": "UIB2033", "name": "IT Project Management", "credits": 3},
                {"code": "UIB2043", "name": "Business Intelligence", "credits": 3},
            ],
            "Semester 5": [
                {"code": "MPU3243", "name": "MPU4 Course", "credits": 3},
                {"code": "UHB3032", "name": "Professional Communication Skills", "credits": 2},
                {"code": "UIB3013", "name": "Information Security", "credits": 3},
                {"code": "UIB3023", "name": "IS Elective I", "credits": 3},
                {"code": "UXX3001", "name": "Minor Elective I", "credits": 3},
            ],
            "Semester 6": [
                {"code": "UHB3042", "name": "Entrepreneurship", "credits": 2},
                {"code": "UIB3033", "name": "IS Elective II", "credits": 3},
                {"code": "UIB3043", "name": "IS Elective III", "credits": 3},
                {"code": "UIB3053", "name": "Data Analytics", "credits": 3},
                {"code": "UXX3002", "name": "Minor Elective II", "credits": 3},
            ],
            "Semester 7": [
                {"code": "UIB4012", "name": "Final Year Project I", "credits": 2},
                {"code": "UIB4023", "name": "IS Elective IV", "credits": 3},
                {"code": "UIB4033", "name": "IS Elective V", "credits": 3},
                {"code": "UXX4001", "name": "Minor Elective III", "credits": 3},
                {"code": "UXX4002", "name": "Minor Elective IV", "credits": 3},
            ],
            "Semester 8": [
                {"code": "UIB4014", "name": "Final Year Project II", "credits": 4},
                {"code": "UIB4043", "name": "IS Elective VI", "credits": 3},
                {"code": "UXX4003", "name": "Minor Elective V", "credits": 3},
                {"code": "UXX4004", "name": "Minor Elective VI", "credits": 3},
            ],
        }
    },
}
